'use strict';

const assert=require('assert');
const fs=require('fs');
const path=require('path');
const relations=require('../bsgt-relations');
const management=require('../bsgt-management');
const root=path.join(__dirname,'..');
const sql=fs.readFileSync(path.join(root,'supabase','34_bsgt_relations_phase5.sql'),'utf8');
const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
let passed=0;
function check(value,message){assert.ok(value,message);passed+=1;}

const shipments=[{id:'s1',operationNo:'BSGTX-1'},{id:'s2',operationNo:'BSGTX-2'}];
let result=relations.evaluateBsgtRelationsAttachments(shipments,[],3);
check(result.missingOptionalCount===4,'both optional files may be missing for every shipment');
check(result.warnings.length===4,'warning list matches missing optional count');
check(!Object.prototype.hasOwnProperty.call(result,'completed'),'optional helper has no blocking completed flag');
check(result.shipments[0].companyLetter===false,'company letter missing state');
check(result.shipments[0].signedStampedLetterhead===false,'letterhead missing state');
result=relations.evaluateBsgtRelationsAttachments(shipments,[{shipment_id:'s1',attachment_type:'company_letter',revision_no:3,is_active:true}],3);
check(result.missingOptionalCount===3,'one optional attachment reduces warning count');
check(result.shipments[0].companyLetter===true,'active current attachment counted');
result=relations.evaluateBsgtRelationsAttachments(shipments,[{shipment_id:'s1',attachment_type:'company_letter',revision_no:2,is_active:true}],3);
check(result.missingOptionalCount===4,'old revision ignored');
result=relations.evaluateBsgtRelationsAttachments(shipments,[{shipment_id:'s1',attachment_type:'company_letter',revision_no:3,is_active:false}],3);
check(result.missingOptionalCount===4,'archived attachment ignored');
check(relations.validateAttachmentFile({type:'application/pdf',size:100}).valid,'PDF accepted');
check(relations.validateAttachmentFile({type:'image/png',size:100}).valid,'PNG accepted');
check(relations.validateAttachmentFile({type:'image/jpeg',size:100}).valid,'JPEG accepted');
check(!relations.validateAttachmentFile({type:'application/javascript',size:100}).valid,'executable rejected');
check(!relations.validateAttachmentFile({type:'application/pdf',size:relations.MAX_FILE_SIZE+1}).valid,'oversized file rejected');
check(relations.statusLabel('sent_to_collecting')==='تم الإرسال للبنك المحصل','sent label');

check(sql.includes('add column if not exists sent_to_collecting_by uuid references public.profiles(id)'),'send actor column');
check(sql.includes('create table if not exists public.trade_collection_relations_attachments'),'relations attachment table');
check(sql.includes("check (attachment_type in ('company_letter', 'signed_stamped_letterhead'))"),'attachment type constraint');
check(sql.includes('trade_collection_relations_attachments_active_key'),'single current active attachment index');
check(sql.includes('Shipment is not linked to this trade file'),'cross-file shipment rejected');
check(sql.includes("values ('trade-collection-documents', 'trade-collection-documents', false)"),'private storage bucket reused');
check(sql.includes("split_part(p_storage_path, '/', 1) <> 'relations'"),'isolated storage path');
check(sql.includes("lower(coalesce(p_mime_type, '')) not in ('application/pdf', 'image/png', 'image/jpeg')"),'server MIME validation');
check(sql.includes("public.has_bsgt_workspace_permission('relations', true)"),'relations edit permission');
check(sql.includes("public.has_bsgt_workspace_permission('relations', false)"),'relations view permission');
check(sql.includes('create or replace function public.get_bsgt_relations_trade_files'),'server-side list RPC');
check(sql.includes("trade_file.status in ('final_accepted', 'sent_to_collecting')"),'relations list status scope');
check(sql.includes('trade_file.company_id = public.bsgt_company_id()'),'BSGT list scope');
check(sql.includes("shipment.bsgt_stage is distinct from 'final_accepted'"),'ready list validates every shipment');
check(sql.includes('create or replace function public.register_bsgt_relations_attachment'),'register RPC');
check(sql.includes('set is_active = false, archived_at = now()'),'replacement archives previous attachment');
check(sql.includes('create or replace function public.archive_bsgt_relations_attachment'),'archive RPC');
check(sql.includes('create or replace function public.send_bsgt_trade_file_to_collecting'),'send RPC');
check(sql.includes("if v_file.status <> 'final_accepted'"),'send only from final accepted');
check(sql.includes("shipment.bsgt_stage = 'final_accepted'"),'linked shipment stage rechecked');
check(sql.includes("set bsgt_stage = 'sent_to_collecting'"),'all linked shipments transition');
check(sql.includes("set status = 'sent_to_collecting'"),'trade file transition');
check(sql.includes('sent_to_collecting_by = auth.uid()'),'send actor saved');
check(sql.includes('sent_to_collecting_at = v_now'),'send time saved');
check(sql.includes("'sent_to_collecting', 'final_accepted', 'sent_to_collecting'"),'audit event created');
check(!/next_trade_collection_operation_no[\s\S]*send_bsgt_trade_file_to_collecting/.test(sql),'send does not generate operation number');
check(!sql.includes("attachment_type = any(v_required)"),'optional relation attachments are not required by send');
check(sql.includes('for update of shipment'),'shipment transition is locked and atomic');
check(html.includes("sb.rpc('get_bsgt_relations_trade_files'"),'UI uses server-side list RPC');
check(html.includes("sb.from('trade_collection_relations_attachments').select('*').eq('trade_file_id',id)"),'one bulk attachment query per detail');
check(html.includes('هذه المرفقات اختيارية ويمكنك المتابعة بدونها'),'nonblocking warning confirmation');
check(html.includes("sb.rpc('send_bsgt_trade_file_to_collecting'"),'send action wired');
check(!html.slice(html.indexOf('async function ensureBsgtFinalPackageAllowed'),html.indexOf('function renderShipmentAcceptanceState')).includes('trade_collection_relations_attachments'),'merge gate ignores relation attachments');
check(!sql.includes('client_company_profiles'),'no client profile asset injection');
const signed=['letter','undertaking','exchange'].map(document_type=>({revision_no:1,document_type,is_active:true}));
check(management.mergeAllowed({bsgtStage:'final_accepted'},{status:'final_accepted',revision_no:1,metadata:{}},signed)===true,'merge allowed at final accepted');
check(management.mergeAllowed({bsgtStage:'sent_to_collecting'},{status:'sent_to_collecting',revision_no:1,metadata:{}},signed)===true,'relations send does not relock merge');
check(passed>=32,`expected at least 32 Phase 5 checks, got ${passed}`);

console.log(`BSGT relations Phase 5: ${passed} checks passed`);
