'use strict';
const assert=require('node:assert/strict');
const {filterFiles,summary,PAGE_SIZE}=require('../bsgt-bank-sent');
const files=Array.from({length:31},(_,i)=>({id:`file-${i}`,operation_no:`TC-2026-${i}`,status:'sent_to_collecting',collecting_bank:i%2?'BANK B':'BANK A',sent_to_collecting_at:`2026-09-${String(i%28+1).padStart(2,'0')}T12:00:00Z`,shipments:[{id:`shipment-${i}`,data:{consignee:i%3?'CLIENT B':'CLIENT A',operationNo:`BSGTX-${i}`,invoiceNo:`INV-${i}`,billNo:`BL-${i}`}}]}));
assert.equal(PAGE_SIZE,10);
assert.equal(filterFiles([...files,{...files[0],status:'final_accepted'},{...files[0],archived_at:'2026-09-20'}]).length,31);
assert.equal(filterFiles(files,{bank:'BANK A',client:'CLIENT A'}).length,6);
assert.equal(filterFiles(files,{search:'inv-30'})[0].id,'file-30');
assert.equal(filterFiles(files,{search:'bl-30'})[0].id,'file-30');
assert.equal(filterFiles(files,{search:'bsgtx-30'})[0].id,'file-30');
assert.equal(filterFiles(files,{bank:'MISSING'}).length,0);
assert.equal(filterFiles(files,{from:'2026-09-27',to:'2026-09-28'}).length,2);
assert.equal(filterFiles(files,{from:'2026-09-28',to:'2026-09-27'}).length,0);
assert.equal(filterFiles(files)[0].id,'file-27');
assert.equal(filterFiles(files,{sort:'oldest'})[0].id,'file-0');
assert.equal(filterFiles(files).slice(30,40).length,1,'last page is reachable');
assert.deepEqual(summary(files),{files:31,shipments:31,banks:2,clients:2});
const multi={...files[0],shipments:[...files[0].shipments,{id:'second',data:{consignee:'OTHER CLIENT'}}]};
assert.equal(filterFiles([multi],{client:'OTHER CLIENT'}).length,1);
assert.equal(summary([multi]).clients,2);
assert.equal(filterFiles([{...files[0],sent_to_collecting_at:null}],{from:'2026-01-01'}).length,0);
assert.equal(filterFiles([{...files[0],shipments:[]}]).length,1,'missing visible shipment data never hides an authorized file');
console.log('Bank-sent filters, summaries, order, multi-client files and page boundaries: passed');
