'use strict';
const assert=require('node:assert/strict');
const {test}=require('node:test');
const fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const D=require('../import-permit-decimal');
test('exact decimal calculations and currency validation',()=>{
  for(const [input,expected] of [['123.456789','123.456789'],['0.000001','0.000001'],['18.170','18.17'],[0.000001,'0.000001'],[1e-7,'0.0000001']])assert.equal(D.decimal(input),expected);
  assert.equal(D.add('123.456789','0.000001'),'123.45679');
  assert.equal(D.add('9007199254740993','0.000001'),'9007199254740993.000001');
  assert.equal(D.multiply('18.170','3.123456789'),'56.75320985613');
  assert.equal(D.divide('0.000001','0.000001'),'1');
  assert.equal(D.divide('1','8'),'0.125');assert.equal(D.divide('1','3'),'1 / 3');
  assert.equal(D.currency('  Sudanese   Pound  '),'Sudanese Pound');
  for(const value of ['','0','-1','Infinity','NaN','1e9999'])assert.equal(D.positive(value),false);
  assert.throws(()=>D.currency('<script>'));assert.throws(()=>D.currency('A'.repeat(65)));
});
test('unit-price display rounds only its quotient to two decimals using exact arithmetic',()=>{
  assert.equal(D.unitPriceDisplay('73400','538'),'136.43');
  assert.equal(D.unitPriceDisplay(D.multiply('20000','3.67'),'538'),'136.43');
  assert.equal(D.unitPriceDisplay('1','8'),'0.13');
  assert.equal(D.unitPriceDisplay('1','3'),'0.33');
  assert.equal(D.unitPriceDisplay('1.999','1'),'2.00');
  assert.equal(D.unitPriceDisplay('0.000001','1'),'0.00');
  assert.equal(D.unitPriceDisplay('0.000001','0.000001'),'1.00');
  assert.equal(D.unitPriceDisplay('9007199254740993.125','1'),'9007199254740993.13');
  assert.throws(()=>D.unitPriceDisplay('1','0'));
  assert.equal(D.divide('73400','538'),'36700 / 269','exact calculation remains unchanged');
});

test('permit API preserves legacy records, decimals, references, authorization and archive pages',async()=>{
  const dir=fs.mkdtempSync(path.join(os.tmpdir(),'permit-api-'));
  const oldEnv={dir:process.env.JAHEZ_DATA_DIR,key:process.env.SUPABASE_SERVICE_ROLE_KEY};
  process.env.JAHEZ_DATA_DIR=dir;process.env.SUPABASE_SERVICE_ROLE_KEY='test-key';
  const file=path.join(dir,'import-permit-invoices.json');
  const data={proformaNo:'PI',proformaDate:'2026-09-16',consignee:'Buyer',consigneeAddress:'Address',portDischarge:'Port',countryOrigin:'China',currency:'USD',convertToAed:true,aedRate:3.67,items:[{commodityId:'1',description:'Goods',hsCode:'123456',unit:'PCE',quantity:18.17,amount:123.456789}]};
  const legacy={id:'old',reference:'BSGT-IP-2026-0001',ownerId:'user',data,createdAt:'2026-09-01',updatedAt:'2026-09-01'};
  const seed=[legacy,...Array.from({length:115},(_,i)=>({...legacy,id:'archive-'+i,reference:'ARCH-'+i,archivedAt:'2026-09-01'}))];
  fs.writeFileSync(file,JSON.stringify(seed));const before=fs.readFileSync(file,'utf8');
  const originalFetch=global.fetch;let role='admin',finance=false,portal=false,profileId='user',active=true;
  global.fetch=async url=>({ok:true,json:async()=>String(url).includes('/auth/')?{id:profileId}:String(url).includes('/profiles?')?[{id:profileId,role,active,display_name:'Tester'}]:String(url).includes('/rpc/has_feature_permission')?finance:String(url).includes('/user_portal_permissions?')&&portal?[{portal_key:'import_permit',can_view:true}]:[]});
  const modulePath=require.resolve('../api/import-permit-invoices');delete require.cache[modulePath];const handler=require(modulePath);
  async function call(method,body,query={}){const res={setHeader(){},status(c){this.code=c;return this;},json(body){this.body=body;return this;}};await handler({method,body,query,headers:{authorization:'Bearer test'}},res);return res;}
  try{
    const list=await call('GET');assert.equal(list.body.records[0].data.items[0].quantity,18.17);
    assert.equal(fs.readFileSync(file,'utf8'),before,'reads do not rewrite the legacy store');
    for(const page of [1,2,12]){const r=await call('GET',null,{status:'archived',page,pageSize:10});assert.equal(r.body.pagination.total,115);assert.equal(r.body.records.length,page===12?5:10);assert.equal(r.body.pagination.page,page);}
    assert.equal((await call('POST',{data:{...data,aedRate:''}})).code,400);
    assert.equal((await call('POST',{data:{...data,aedRate:'0'}})).code,400);
    assert.equal((await call('POST',{data:{...data,currency:'<bad>'}})).code,400);
    const payload={...data,currency:'Sudanese Pound',aedRate:'0.000001',items:[{...data.items[0],quantity:'18.170',amount:'123.456789'},{...data.items[0],quantity:'0.000001',amount:'0.000001'}]};
    const save=await call('POST',{data:payload});assert.equal(save.code,200);
    assert.equal(save.body.record.data.currency,'Sudanese Pound');assert.equal(save.body.record.data.aedRate,'0.000001');
    assert.deepEqual(save.body.record.data.items.map(i=>[i.quantity,i.amount]),[['18.17','123.456789'],['0.000001','0.000001']]);
    assert.deepEqual(JSON.parse(fs.readFileSync(file)).find(r=>r.id==='old'),legacy,'unrelated old numeric values unchanged');
    const id=save.body.record.id,ref=save.body.record.reference;
    const edit=await call('POST',{id,data:{...payload,proformaNo:'EDIT'}});assert.equal(edit.body.record.reference,ref);
    await call('PATCH',{id,archived:true});assert.equal((await call('POST',{id,data:payload})).code,409);
    await call('PATCH',{id,archived:false});assert.equal((await call('GET')).body.records.find(r=>r.id===id).data.proformaNo,'EDIT');
    const legacyEdit=await call('POST',{id:'old',data:{...data,proformaNo:'OLD-EDIT'}});assert.equal(legacyEdit.body.record.reference,legacy.reference);assert.equal(legacyEdit.body.record.data.items[0].amount,'123.456789');
    const noConversion=await call('POST',{data:{...data,convertToAed:false,aedRate:''}});assert.equal(noConversion.code,200);assert.equal(noConversion.body.record.data.aedRate,'');
    const autoData={...data,proformaNo:'',proformaDate:'2026-09-20'};
    const firstAuto=await call('POST',{data:autoData});
    assert.equal(firstAuto.body.record.data.proformaNo,'BSGTP260001');
    const autoId=firstAuto.body.record.id;
    const repeatAuto=await call('POST',{id:autoId,data:{...autoData,proformaDate:'2026-09-21'}});
    assert.equal(repeatAuto.body.record.data.proformaNo,'BSGTP260001','editing or blanking an existing number does not renumber it');
    const manual=await call('POST',{id:autoId,data:{...autoData,proformaNo:'READY-123'}});
    assert.equal(manual.body.record.data.proformaNo,'READY-123');
    assert.equal(JSON.parse(fs.readFileSync(file)).find(r=>r.id===autoId).proformaSequence,'1','manual replacement retains sequence allocation');
    await call('PATCH',{id:autoId,archived:true});
    const concurrent=await Promise.all(Array.from({length:4},()=>call('POST',{data:{...autoData,proformaDate:'2027-01-02'}})));
    assert.deepEqual(concurrent.map(r=>r.body.record.data.proformaNo),[2,3,4,5].map(n=>`BSGTP27000${n}`));
    await call('PATCH',{id:autoId,archived:false});
    const manualPattern=await call('POST',{data:{...autoData,proformaNo:'BSGTP-09-20-2026-6'}});
    assert.equal(manualPattern.body.record.data.proformaNo,'BSGTP-09-20-2026-6');
    const afterManual=await call('POST',{data:autoData});assert.equal(afterManual.body.record.data.proformaNo,'BSGTP260007');
    delete require.cache[modulePath];const restartedHandler=require(modulePath);
    const restartResponse={setHeader(){},status(c){this.code=c;return this;},json(body){this.body=body;return this;}};
    await restartedHandler({method:'POST',body:{data:autoData},headers:{authorization:'Bearer test'}},restartResponse);
    assert.equal(restartResponse.body.record.data.proformaNo,'BSGTP260008','sequence survives server restart');
    await call('POST',{data:{...autoData,proformaNo:'BSGTP260009'}});
    assert.equal((await call('POST',{data:autoData})).body.record.data.proformaNo,'BSGTP260010','automatic numbering skips manually assigned compact numbers');
    assert.equal(JSON.parse(fs.readFileSync(file)).find(r=>r.id===manualPattern.body.record.id).data.proformaNo,'BSGTP-09-20-2026-6','existing dashed numbers are preserved');
    assert.equal(JSON.parse(fs.readFileSync(file)).find(r=>r.id==='archive-0').data.proformaNo,'PI','untouched old invoices keep their numbers');
    role='editor';assert.equal((await call('GET')).code,403);
    role='staff';profileId='finance-user';finance=true;
    const storedBeforeFinance=fs.readFileSync(file,'utf8');
    const financeList=await call('GET');assert.equal(financeList.code,200);
    assert.ok(financeList.body.records.some(r=>r.ownerId==='user'),'finance sees invoices made by other employees');
    const updates=financeList.body.records.map(r=>r.updatedAt);
    assert.deepEqual(updates,updates.slice().sort().reverse(),'newest updates first');
    assert.equal((await call('GET',null,{search:'OLD-EDIT'})).body.records.length,1);
    assert.equal((await call('GET',null,{status:'archived',page:12,pageSize:10})).body.records.length,5);
    for(const body of [{data:payload},{id:'old',data:payload}])assert.equal((await call('POST',body)).code,403);
    for(const archived of [true,false])assert.equal((await call('PATCH',{id:'old',archived})).code,403);
    portal=true;assert.equal((await call('POST',{data:payload})).code,403,'finance remains read-only even with the legacy portal grant');
    assert.equal(fs.readFileSync(file,'utf8'),storedBeforeFinance,'finance reads and denied writes never rewrite the store');
    active=false;assert.equal((await call('GET')).code,403);active=true;
    finance=false;assert.equal((await call('GET')).body.records.length,0,'ordinary portal employee is still owner-scoped');
    portal=false;assert.equal((await call('GET')).code,403,'revoking finance access immediately denies further reads');
  }finally{
    global.fetch=originalFetch;delete require.cache[modulePath];
    for(const [key,value] of [['JAHEZ_DATA_DIR',oldEnv.dir],['SUPABASE_SERVICE_ROLE_KEY',oldEnv.key]])if(value===undefined)delete process.env[key];else process.env[key]=value;
    fs.rmSync(dir,{recursive:true,force:true});
  }
});
