const crypto=require('crypto');
const R='congstars_word_refresh',S='congstars_word_state';
const cookies=h=>Object.fromEntries((h||'').split(';').map(x=>x.trim().split('=').map(decodeURIComponent)).filter(x=>x[0]));
const ck=(n,v,a)=>n+'='+encodeURIComponent(v)+'; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age='+a;
const cfg=()=>{const{MS_CLIENT_ID:id,MS_CLIENT_SECRET:secret,MS_TENANT_ID:tenant}=process.env;if(!id||!secret||!tenant)throw Error('Microsoft Graph server settings are incomplete.');return{id,secret,tenant}};
const cb=req=>`https://${req.headers['x-forwarded-host']||req.headers.host}/api/microsoft?action=callback`;
async function token(p){const c=cfg(),r=await fetch('https://login.microsoftonline.com/'+c.tenant+'/oauth2/v2.0/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams(p)}),j=await r.json();if(!r.ok)throw Error(j.error_description||'Microsoft authentication failed');return j}
async function graph(access,path,options){const r=await fetch('https://graph.microsoft.com/v1.0'+path,Object.assign({headers:{Authorization:'Bearer '+access}},options));if(!r.ok)throw Error('تعذّر الوصول إلى ملف Word: '+await r.text());return r}
async function itemByName(access,name){const r=await fetch('https://graph.microsoft.com/v1.0/me/drive/root:/'+encodeURIComponent(name)+':?$select=id,name,webUrl',{headers:{Authorization:'Bearer '+access}});if(r.status===404)return null;if(!r.ok)throw Error('تعذّر الوصول إلى ملف Word: '+await r.text());return r.json()}
const waitPage=()=>'<main dir="rtl" style="font-family:Tahoma,sans-serif;max-width:520px;margin:80px auto;line-height:1.9"><h1>جارٍ إنشاء نسخة Word المستقلة</h1><p>تم بدء نسخ القالب، انتظر بضع ثوانٍ ثم اضغط الزر لفتحها في Word Online.</p><a href="/api/microsoft?action=open-test" style="display:inline-block;padding:10px 18px;background:#1769e8;color:white;border-radius:8px;text-decoration:none">فتح النموذج</a></main>';
module.exports=async(req,res)=>{const a=req.query.action||'status',c=cookies(req.headers.cookie);try{if(a==='connect'){const s=crypto.randomBytes(24).toString('base64url'),x=cfg(),q=new URLSearchParams({client_id:x.id,response_type:'code',redirect_uri:cb(req),response_mode:'query',scope:'offline_access User.Read Files.ReadWrite',state:s,prompt:'select_account'});res.setHeader('Set-Cookie',ck(S,s,600));return res.redirect(302,'https://login.microsoftonline.com/'+x.tenant+'/oauth2/v2.0/authorize?'+q)}if(a==='callback'){if(!req.query.code||req.query.state!==c[S])throw Error('Invalid or expired connection request');const x=cfg(),t=await token({client_id:x.id,client_secret:x.secret,code:req.query.code,redirect_uri:cb(req),grant_type:'authorization_code'});res.setHeader('Set-Cookie',[ck(R,t.refresh_token,7776000),ck(S,'',0)]);return res.status(200).send('<h1 dir="rtl">تم ربط Word Online بنجاح</h1><p dir="rtl">يمكنك إغلاق هذه الصفحة والعودة للموقع.</p>')}if(!c[R])return res.json({connected:false,connectUrl:'/api/microsoft?action=connect'});const x=cfg(),t=await token({client_id:x.id,client_secret:x.secret,refresh_token:c[R],grant_type:'refresh_token',scope:'offline_access User.Read Files.ReadWrite'});if(t.refresh_token)res.setHeader('Set-Cookie',ck(R,t.refresh_token,7776000));if(a==='open-test'){const name='منشأ دبي التجريبي ليس للتداول.docx',copy=await itemByName(t.access_token,name);if(copy)return res.redirect(302,copy.webUrl);const sourceSearch=await graph(t.access_token,'/me/drive/root/search(q=\''+encodeURIComponent('تصميم مشابه')+'\')?$select=id,name&$top=20').then(r=>r.json()),source=sourceSearch.value.find(f=>/\.docx$/i.test(f.name));if(!source)throw Error('لم يتم العثور على ملف تصميم مشابه.docx في OneDrive. ارفعه أولاً إلى OneDrive ثم أعد المحاولة.');await graph(t.access_token,'/me/drive/items/'+source.id+'/copy',{method:'POST',headers:{Authorization:'Bearer '+t.access_token,'Content-Type':'application/json'},body:JSON.stringify({parentReference:{id:'root'},name})});return res.status(202).send(waitPage())}return res.json({connected:true})}catch(e){return res.status(500).json({connected:false,error:e.message})}};
